version: "2.2"
services:
    explorer:
        scale: 1
        build:
            context: ./services/explorer/docker
            dockerfile: Dockerfile
            args:
                - TZ=${TZ}
                - USER=explorer
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONPATH=${EXPLORER_SRC}
            - CONFIG_DIR=${CONFIG_DIR}
            - JUPYTER_CONFIG=${JUPYTER_CONFIG}
            - DEFAULT_CONFIG=${CONFIG_DIR}/explorer/default_config.yml
        user: 1000:1000
        working_dir: ${EXPLORER_SRC}/scripts
        command: ["sh", "common/start_jupyter.sh"]
        volumes:
            - ./services/explorer/config:${CONFIG_DIR}
            - ./services/explorer/src/notebooks:${NOTEBOOKS_DIR}
            #Library code
            - ./library/scripts:${EXPLORER_SRC}/scripts
            - ./library/python/models/interface:${EXPLORER_SRC}/models/interface
            - ./library/python/utils:${EXPLORER_SRC}/utils
            #Data (Temporary)
            - ./data:/notebooks/data
        ports:
            - 8888:8888

    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic

    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data02:/usr/share/elasticsearch/data
        ports:
            - 9201:9201
        networks:
            - elastic

    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - data03:/usr/share/elasticsearch/data
        ports:
            - 9202:9202
        networks:
            - elastic

    kib01:
        image: docker.elastic.co/kibana/kibana:7.5.2
        container_name: kib01
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: http://es01:9200
        networks:
            - elastic

volumes:
    data01:
        driver: local
    data02:
        driver: local
    data03:
        driver: local

networks:
    elastic:
        driver: bridge
